### ISSUE TITLE
Food Pies giving huge amounts of calories with realistic setting.

### ISSUE THREAD

**Issue by MrSamsa** [GruffCassquatch/FoodTweaker#5]
Pie recipes like venison pie are giving waaay too many calories with the realistic setting.
After checking the math, it appears that any pies are getting x3 the calorie value set plus whatever bonus cooking skill offers.

For example, venison is supposed to give 480 calories per pie out of 3 however each pie is actually over 1700 which happens to be 480 x 3 + 20% cooking bonus I have atm.

I realise FoodTweaker hasent been updated but, I thought this might be useful if someone looks here..

**Comment by GruffCassquatch** [comment]
I am not currently maintaining this or any other mod. You can find and contact the modders who have updated this mod most recently on TLD Modding Discord, but I don't think anyone is currently actively maintaining it.

**Comment by GruffCassquatch** [comment]
See the readme for details on who has last maintained the mod.
